version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - attach_workspace:
          at: ~/tmp
      - run: 
          name: Build
          command: | 
            yarn install --frozen-lockfile
            yarn build
      - persist_to_workspace:
          root: .
          paths: 
            - dist
            - deploy.sh

  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/tmp
    steps:
      - attach_workspace:
          at: ~/tmp
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3
          command: ./deploy.sh


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build