version: 2
jobs:
  build_and_deploy:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: 
          name: Build
          command: | 
            yarn install --frozen-lockfile
            yarn build
      - deploy:
          name: Deploy to S3
          command: ./deploy.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_deploy